[동적계획법과 최단경로] 11월 11일 -ing
Altu-Bitu/Altu-Bitu_HW pull request #17
Opened 2021-11-11 00:33 UTC by hyunk-go

15683을 어떤 자료구조나 방식을 써서 접근하면 좋을지 궁금합니다. cctv구간을 업데이트할때 그냥 #의 개수가 가장 많은 방향을 선택하는 식으로 update를 하면 되는걸까요?
2615번은 예제는 맞았는데 정답은 틀려서 오류가 뭔지 궁금합니다.
9019번은 제 논리에서 무엇이 틀렸는지 알고싶습니다.
감사합니다!!:>

2021-11-11 03:06 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 질문 주신 부분들은 코멘트로 남겨놓았어요
만약 추가 힌트 필요하시면 말해주세요!

수정하시고 리뷰어로 저 불러주세요~

2021-11-11 03:06 UTC, HyunJiLim0406 commented on 11월 9일/9019.cpp
> +		}
이 부분 한 번에 처리할 수 있습니다!
문제에선 0~10,000의 십진수를 저장할 수 있다고 나와있어요
1에서 1을 빼서 9999가 되는게 아니라 0에서 1을 빼서 9999가 되는겁니다!

2021-11-11 03:06 UTC, HyunJiLim0406 commented on 11월 9일/9019.cpp
> +		if (!check[(a * 2) / SIZE])
여기도 문제 한 번 다시 읽어주세요!

2021-11-13 08:28 UTC, HyunJiLim0406 requested changes
p1
수정하신 문제 확인했습니다!
잘 수정해주셨네요. 안풀리는 문제들에 대해서도 추가 힌트 드렸습니다. 주석으로 달아주신 질문에 대한 답변도 해드렸구요! 만약 설명이 불충분하다면 말해주세요

수정하시거나 추가 힌트가 필요하면 저 불러주세요!

2021-11-13 08:28 UTC, HyunJiLim0406 commented on 11월 9일/2615.cpp
> +		flag = 0;
왼쪽부터 세는건 저희 기준이라 그렇습니다
19x19를 다 그리긴 어려우니 그냥 간단하게 표시하면

00111111000

라고 할게요.
인덱스를 0부터 시작한다고 가정하고 (0, 3)에 대해 탐색을 한다면 5개만 잡힐거예요.
하지만 왼쪽에 돌이 있고 육목이 되기 때문에 답이 아니란걸 알 수 있어요!

2021-11-13 08:28 UTC, HyunJiLim0406 commented on 11월 9일/2615.cpp
> +int main()
제가 왜 지난번에 런타임 에러가 뜨진 않으시냐고 여쭤봤는지 잘 생각해보세요!
저희가 인덱스를 많이 바꿔가며 접근하는 이런류의 문제를 풀 때마다 항상 조심해야 한다고 한게 있었어요

2021-11-13 08:28 UTC, HyunJiLim0406 commented on 11월 9일/2615.cpp
> +				result = winner(matrix,i,j,result);
result 값이 어떻게 변화하는지 확인해보세요!

2021-11-13 08:28 UTC, HyunJiLim0406 commented on 11월 9일/9019.cpp
> +int SIZE = 10e4;
이게 어떤 값을 의미하는걸까요?

2021-11-13 10:25 UTC, hyunk-go commented on 11월 9일/9019.cpp
> +int SIZE = 10e4;
10000미만만 받을수있어서 크기로 할당한거였어요!

2021-11-13 10:32 UTC, HyunJiLim0406 commented on 11월 9일/9019.cpp
> +int SIZE = 10e4;
이게 정말 10000인지 출력해보세요!

2021-11-13 10:48 UTC, hyunk-go commented on 11월 9일/9019.cpp
> +int SIZE = 10e4;
앗 이게 문제였군요!ㅋㅋㅋ큐ㅠㅠㅠㅠ계속 다른거 부여잡고 있었네요! 감사합니다:)

2021-11-13 11:26 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 알고보니 다 사소한 실수들이었네요!
15683번을 푸시는 것도 좋지만 이미 푼 문제를 리팩토링하는 것도 좋아요
문제를 풀 때는 답을 맞춰야 한다는 생각때문에 여유가 없어져 비효율적인 코드를 짜기도 하거든요. 사실 제가 자주 이래요 핳...

문제를 푼 뒤 침착하게 코드를 다시 살펴보면 중복된 부분이나, 필요없는 연산같은게 보입니다!
리팩토링 과정에서도 배울 수 있는게 많으니 한 번 시도해보세요!

문제 추가되거나 제가 필요한 경우가 생기면 불러주세요!

2021-11-13 11:26 UTC, HyunJiLim0406 commented on 11월 9일/9019.cpp
> +		int na = (x - 1) < 0 ? SIZE - 1 : x - 1;
삼항연산자를 사용하지 않는 방법도 있어요!

2021-11-13 11:26 UTC, HyunJiLim0406 commented on 11월 9일/2615.cpp
> +ci winner(int matrix[19][19],int i, int j,ci result)
p1
이제 잘 돌아가지만 공통되거나 하드코딩된 부분들이 많아요. 리팩토링을 해보면 어떨까요?
저희 상하좌우로 이동할 때 방향을 어떻게 잡았었나요? 이 문제에선 어떻게 적용할 수 있을까요?
그리고 모든 방향에 대해 5개의 돌을 확인하고 마지막으로 육목 여부를 체크하는 부분은 다 공통되는 부분입니다.

result를 인자로 넘기면서 갱신하기보다는 승자가 나오면 메인에서 break하는게 더 자연스러울 것 같아요!
이기는 경우의 수는 단 하나라고 문제에 주어지니까요!

이번 실수가 하드코딩을 하면서 나온 실수기도 한 만큼 리팩토링을 고려해보셔도 좋습니다!

2021-11-14 14:14 UTC, hyunk-go commented on 11월 9일/2615.cpp
> +ci winner(int matrix[19][19],int i, int j,ci result)
15683을 만약 못풀면 추가제출을 할거 같은데 그렇게 되면 나머지 문제는 머지해도 되나용?

2021-11-15 09:07 UTC, HyunJiLim0406 approved these changes
p2
수고하셨습니다! 잘 푸셨지만 15683, 2615번은 꼭 리팩토링 하셔야해요!
코드를 직접 보면서 중복되는 부분을 줄여나가거나 샘플코드를 참고하셔도 좋습니다.
특히 15683번은 기술블로그 해설이 같이 나갈 예정이라 보시면 좋습니다

이제 머지하셔도 됩니다!

2021-11-15 09:07 UTC, HyunJiLim0406 commented on 11월 9일/15683.cpp
> +		}
여기서 공통되는 부분이 보이실까요?

2021-11-15 09:07 UTC, HyunJiLim0406 commented on 11월 9일/15683.cpp
> +}
이 함수 없이 그냥 temp = matrix로 하셔도 됩니다~

2021-11-15 09:07 UTC, HyunJiLim0406 commented on 11월 9일/15683.cpp
> +
여기도 dr, dc를 활용하면 중복이 줄어들겠네요!

2021-11-16 01:53 UTC, merged